export const SAMPLE_CONTACTS = [
  {
    first_name: 'Alex',
    last_name: 'Brian',
    email: 'brian.everhard@exprealty.com',
    phone: '15122890670',
    source: 'Showing',
    company: 'ERA Brokerage',
    city: 'Scranton',
    website: 'https://app.crmgrow.com/',
    state: 'Alabama',
    zip: '18502',
    address: '698 E Milwaukee Ave',
    status: 'Cold',
    birthday: '2/24/1992',
    note: 'We met on facebook and said about the CRMgrow',
    tags: 'active, eXp Realty',
    country: 'US',
    secondary_email: '',
    secondary_phone: '',
    deal: 'Deal1'
  },
  {
    first_name: 'ALicia',
    last_name: 'Barefoot',
    email: 'alicia.barefoot@exprealty.com',
    phone: '19199122125',
    source: 'networking',
    company: 'Watson William',
    city: 'Aston',
    website: 'https://app.crmgrow.com/',
    state: 'Alabama',
    zip: '19014',
    address: '555 N Madison Ave',
    status: 'New',
    birthday: '10/12/2001',
    note: "We met at an open house and we've said about the eXp Realty.",
    tags: 'active, eXp Realty',
    country: 'CA',
    secondary_email: '',
    secondary_phone: '',
    deal: 'Deal1'
  },
  {
    first_name: 'Adam',
    last_name: 'Brandvein',
    email: 'Adam.Brandvein@exprealty.com',
    phone: '13149107562',
    source: 'Openhouse',
    company: 'Re/Max',
    city: 'Chicago',
    website: 'https://app.crmgrow.com/',
    state: 'Alabama',
    zip: '60632',
    address: '',
    status: 'Hot',
    birthday: '7/6/1986',
    note: '',
    tags: 'active, eXp Realty',
    country: '',
    secondary_email: '',
    secondary_phone: '',
    deal: 'Deal2'
  },
  {
    first_name: 'Adnanahmic',
    last_name: '',
    email: 'adnanahmic203@gmail.com',
    phone: '(248) 429-9221',
    source: 'Showing',
    company: 'Keller William',
    city: '',
    website: 'https://app.crmgrow.com/',
    state: '',
    zip: '10011',
    address: '67 W North Road',
    status: 'Warm',
    birthday: '1/22/2003',
    note: 'He is excited about what I explained about eXp',
    tags: 'free, eXp Realty',
    country: '',
    secondary_email: 'adnanahmic2345@gmail.com',
    secondary_phone: '15062341456',
    deal: 'Deal3'
  },
  {
    first_name: 'Adrena',
    last_name: 'Holman',
    email: 'adrena.holman@exprealty.com',
    phone: '15122890670',
    source: 'facebook',
    company: '',
    city: 'New York',
    website: 'https://app.crmgrow.com/',
    state: '',
    zip: '',
    address: '698 E Milwaukee Ave',
    status: 'Cold',
    birthday: '3/4/1997',
    note: '',
    tags: 'active, eXp Realty',
    country: '',
    secondary_email: '',
    secondary_phone: '',
    deal: 'Deal3'
  },
  {
    first_name: 'Affiliate',
    last_name: 'Test',
    email: 'beforedawn018@gmail.com',
    phone: '+1 201-552-5651',
    source: 'Met at bar',
    company: '',
    city: 'Las Cruces',
    website: 'https://app.crmgrow.com/',
    state: '',
    zip: '88011',
    address: '91234 S Green St',
    status: 'Warm',
    birthday: '8/7/1999',
    note: 'Friend of mine connected us',
    tags: 'free, eXp Realty',
    country: '',
    secondary_email: '',
    secondary_phone: '',
    deal: 'Deal2'
  }
];
