name: TeamGrow Build to s3
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2

      - name: Install NPM v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Yarn install...
        run: npm install yarn -g

      - name: NPM install...
        run: yarn install

      - name: Build frontend
        run: node --max-old-space-size=8192 node_modules/@angular/cli/bin/ng build --configuration=production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Upload to AWS
        run: |
          aws s3 rm s3://teamgrow-staticsite-green/ --recursive
          aws s3 cp dist/crmgrow s3://teamgrow-staticsite-green/ --recursive --acl public-read

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: teamgrow-staticsite-green
          dist-id: EFW5LJQM4RH8B
          invalidation: / *
